(global-linum-mode 1)
(global-auto-revert-mode t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(require 'recentf)
(recentf-mode 1)
(delete-selection-mode 1)
(setq recentf-max-menu-items 25)
(add-hook 'after-init-hook 'global-company-mode)
(add-hook 'emacs-lisp-mode-hook 'show-paren-mode)
(provide 'init-better-defaults)
